### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Bhargav-Rao** [Bhargav-Rao/NATOBot#1]
Use this issue to report any Feature Requests. They can be of the type,

 - **Additional Filters** : They extend the `Validator` and return only those results that pass that filter. 
 - **Blacklisting Keywords** : Of the type, *Please help*, *How can I*, etc

**Comment by ankitagrawal2411** [comment]
1)I am also facing the same issue
2) Please help me
3)can you Please him me

**Comment by Bhargav-Rao** [comment]
This has been integrated with the bot as a command. Thanks
